#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Application;

require_once __DIR__.'/vendor/autoload.php';

$input = new ArgvInput();
$application = new Application('My Console Application', '1.0.0');

// Register commands here if needed

$status = $application->run($input);

exit($status);
